--- 
title: "Sphaerularia-Bombus infection RNA-Seq study"
output: plot_combined_go_terms_barchart.html
author: Joe Colgan (joscolgan)
--- 

## Introduction:
This script takes two heatmaps saved R objects as input and generates a combined multi-image plot.
The output is a multi-image plot.

```{r, message=FALSE}
# Load libraries; install from scratch if needed
libraries <- c("ggplot2",
               "reshape2",
               "scales",
               "ggpubr",
               "grid",
               "XML")
for (lib in libraries) {
    if (require(package = lib, character.only = TRUE)) {
        print("Successful")
    } else {
        print("Installing")
        source("https://bioconductor.org/biocLite.R")
        library(lib, character.only = TRUE )
    }
}
## Assign path for output:
output <- "results/barchart_figure"
dir.create(output, recursive = TRUE)
```

Generate a combined heatmap:

```{r, message = FALSE}
## Load objects:
load("./input/diapause_go_term_plot.Rdata")
load("./input/postdiapause_go_term_plot.Rdata")

## Generate a combined plot:
ggarrange(diapause_terms_plot,
          postdiapause_terms_plot,
          ncol = 1,
          nrow = 2,
          align = "hv",
          labels = c("A", "B"),
          heights = c(1.0, 2.2),
          common.legend = TRUE)

## Save output:
ggsave(paste(output,
             "/combined_barchart.png",
             sep = ""),
       width = 10,
       height = 10)
```

Run lintr

```{r, message = FALSE}
## Run lintr:
lintr::lint(file = "./plot_combined_go_terms.Rmd")
```